version: "3"

services:
  app:
    image: node:latest
    ports:
      - 3000:3001
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongouser:password@db:27017
      - DB_NAME=test
    volumes:
      - ./:/app
    links:
      - db
    working_dir: "/app"
    command: ["npm", "start"]
  
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./init_db.js:/docker-entrypoint-initdb.d/init_db.js